export const jobs = [
  { title: "", isRead: true },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
  { title: "", isRead: false },
];
